### PR TITLE
Feat/inventory

### PR DESCRIPTION
**Pull request by dhafinn**
**Summary:**
1. Done slicing inventory page
2. Done slicing add inventory item page 
3. Add modifier in custom button
4. Add placeholder in custom edit text

### CODE REVIEW

**Comment by rifqifarelmuhammad** [comment]
Can you add a padding between the bottom and the last row of cards pin?
image

**Comment by rifqifarelmuhammad** [comment]
It seems we can remove the excessive padding here, pin, considering there are no item photo
image

**Comment by dhafinn** [comment]
> It seems we can remove the excessive padding here, pin, considering there are no item photo image

yang ini sengaja gua ttp gituin biar ga plain bgt

**Comment by dhafinn** [comment]
> Can you add a padding between the bottom and the last row of cards pin? image

wait gua lupa udah ada bottom bar

**Review by rifqifarelmuhammad — APPROVED** [review]
I see that now the home screen uses cartoon image, so just make sure that once the cards are added, the issue I mentioned earlier is resolved. Everything else ltgm, nice work, pin!

**Pull request merged**
