### PR TITLE
Integrate Profile with API

### PR DESCRIPTION
**Pull request by rifqifarelmuhammad**
In this PR, I integrated the edit profile page with the real API

### CODE REVIEW

**Review by dhafinn — COMMENTED** [review]
ini placeholdernya belum diganti kah ki?
image

**Comment by dhafinn** [comment]
eh astaga bentar lupa ganti BASE_URL

**Review by dhafinn — COMMENTED** [review]
error when try updating profile
image

**Comment by rifqifarelmuhammad** [comment]
> error when try updating profile

Could you explain further the steps you took leading up to the error pin?

**Review by dhafinn — APPROVED** [review]
should be good, the error probably on my local device

**Comment by rifqifarelmuhammad** [comment]
thanks bro

**Pull request merged**
